/*
 * - PAC-Tool - 
 * Tool for understanding basics and computation of PAC (Pompe à Chaleur)
 * Copyright (C) 2016 christian.klugesherz@gmail.com
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License (version 2)
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */
package gui;

import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JTextPane;
import javax.swing.event.HyperlinkListener;
import computation.Misc;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.EventQueue;
import javax.swing.event.HyperlinkEvent;
import java.io.IOException;
import java.net.URISyntaxException;

public class WinAbout extends JInternalFrame {

	private static final long serialVersionUID = 1L;

	// -------------------------------------------------------
	// 					INSTANCE VARIABLES
	// -------------------------------------------------------

	// -------------------------------------------------------
	// 				TEST THE APPLICATION STANDALONE 
	// -------------------------------------------------------
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {

					WinAbout frame = new WinAbout();
					frame.setVisible(true);

					// <<<<----- FOR TEST CREATE A FRAME WITH JDesktopPane
					JFrame frameM = new JFrame();
					JDesktopPane desktopPaneMain = new JDesktopPane();
					frameM.getContentPane().add(desktopPaneMain, BorderLayout.CENTER);
					frameM.setBounds(100, 10, 700, 700);
					frameM.setVisible(true);
					desktopPaneMain.add(frame); 
					// ----------------->>>>

				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}


	// -------------------------------------------------------
	// 						CONSTRUCTOR
	// -------------------------------------------------------
	/**
	 * Create the application.
	 */
	public WinAbout() {
		initialize();
	}

	// -------------------------------------------------------
	// 							METHOD
	// -------------------------------------------------------

	// -------------------------------------------------------
	// 				 GENERATED BY WIN BUILDER
	// -------------------------------------------------------
	/**
	 * Initialize the contents of the 
	 */
	private void initialize() {
		setTitle("About");
		setFrameIcon(new ImageIcon(WinCompressor.class.getResource("/gui/images/PAC-Tool_16.png")));
		setIconifiable(true);
		setClosable(true);
		setBounds(100, 1, 370, 152);
		setResizable(false);

		getContentPane().setBackground(Color.WHITE);
		getContentPane().setLayout(null);


		JTextPane txtpnabout = new JTextPane();
		txtpnabout.setEditable(false);
		txtpnabout.addHyperlinkListener(new HyperlinkListener() {
			public void hyperlinkUpdate(HyperlinkEvent e) {
				if (e.getEventType().equals(HyperlinkEvent.EventType.ACTIVATED)) {
					try {
						Desktop.getDesktop().mail(e.getURL().toURI());
					} catch (IOException e1) {
						throw new RuntimeException(e1);
					} catch (URISyntaxException e1) {
						throw new RuntimeException(e1);
					}
				}
			}
		});
		txtpnabout.setContentType("text/html");
		txtpnabout.setText("<span\r\n style=\"font-family: Helvetica,Arial,sans-serif; color: rgb(102, 102, 204);\"><span\r\n style=\"font-weight: bold;\">\r\nPAC-Tool:" + Misc.PACTool_Version +"</span><br>\r\n&nbsp;&nbsp;&nbsp; Outil pour Pompe \u00E0 Chaleur <br>\r\n<br>\r\n<b>Auteur:</b>\r\nChristian\r\nKlugesherz<br>\r\n<b>email:</b>\r\n<a href=\"mailto:christian.klugesherz@gmail.com?Subject=PAC-Tool\"\r\n target=\"_top\">christian.klugesherz@gmail.com</a></span>\r\n");
		txtpnabout.setBounds(84, 11, 275, 111);

		getContentPane().add(txtpnabout);

		JLabel lblNewLabel = new JLabel("");
		lblNewLabel.setIcon(new ImageIcon(WinAbout.class.getResource("/gui/images/PAC-Tool_64.png")));
		lblNewLabel.setBounds(10, 11, 64, 64);
		getContentPane().add(lblNewLabel);
	}

}
